
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_matmul.ipynb
from pathlib import Path
from IPython.core.debugger import set_trace
import pickle, gzip, math, torch, matplotlib as mpl
import matplotlib.pyplot as plt
from torch import tensor

from torchvision import datasets, transforms


def get_mnist_data():
    transform = transforms.Compose([transforms.ToTensor(),])
    trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)

    x_train, y_train = zip(*trainset)
    x_train = torch.tensor([x.view(28 * 28).numpy() for x in x_train])
    y_train = torch.tensor(y_train)

    return x_train, y_train

def near(a,b):
    return torch.allclose(a, b, rtol=1e-3, atol=1e-5)